export const sloganText1 = " yo... it's all good baby... all good "

export const projectList = [
  {
    id: "artasce-company-portal",
    name: "Artasce Creative Company Portal",
    thumb: "thumb-artasce-creative-portal.jpg",
    landing: "landing-artasce-company-portal.jpg",
    desc: "briefInformation ac portal here",
    url: "https://artasce-company.web.app/",
  },
  {
    id: "coinwire",
    name: "coinwire",
    thumb: "thumb-coinwire.jpg",
    landing: "landing-coinwire.jpg",
    desc: "info for it here...",
    url: "https://coinwire.web.app/",
  },
  {
    id: "modolla",
    name: "modolla",
    thumb: "thumb-modolla.jpg",
    landing: "landing-modolla.jpg",
    desc: "modolla info...",
    url: "https://modolla-wallet.web.app/",
  },
  {
    id: "mademoiselle",
    name: "mademoiselle",
    thumb: "thumb-mademoiselle.jpg",
    landing: "landing-mademoiselle.jpg",
    desc: "briefInformation mademoiselle",
    url: "https://mademoiselle.netlify.app/",
  },
  {
    id: "mademoiselle-collections",
    name: "mademoiselle-collections",
    thumb: "thumb-mademoiselle-collections.jpg",
    landing: "landing-mademoiselle-collections.jpg",
    desc: "briefInformation mademoiselle collections",
    url: "https://mademoiselle-collections.netlify.app/",
  },
  {
    id: "voya-destinations",
    name: "voya-destinations",
    thumb: "thumb-voya-destinations.jpg",
    landing: "landing-voya-destinations.jpg",
    desc: "briefInformation for voya-destinations",
    url: "https://voya-destinations.web.app/",
  },
  {
    id: "tailwind-templates",
    name: "tailwind-templates",
    thumb: "thumb-tailwind-templates.jpg",
    landing: "landing-tailwind-templates.jpg",
    desc: "briefInformation about tailwind templates here",
    url: "https://tailwindcss-templates.vercel.app/",
  },
  {
    id: "dashboard-intelligence",
    name: "dashboard-intelligence",
    thumb: "thumb-dashboard-intelligence.jpg",
    landing: "landing-dashboard-intelligence.jpg",
    desc: "dashboard-intelligence briefInformation",
    url: "https://dashboard-intelligence.vercel.app/",
  },
]
