export const projectList = [
  {
    id: "artasce-client-portal",
    name: "Artasce Creative Client Portal",
    thumb: "/images/projects/thumbs/artasce-client-portal.jpg",
    landing: "/images/projects/landings/artasce-client-portal.jpg",
    desc: "Client Portal site with Vue 3, Firebase Auth, Firebase Functions and more.",
    url: "https://artasce-company.web.app/",
    gitUrl: "https://github.com/caicodes/",
  },
  {
    id: "coinwire",
    name: "Coinwire",
    thumb: "/images/projects/thumbs/coinwire.jpg",
    landing: "/images/projects/landings/coinwire.jpg",
    desc: "Coinwire Live Cryptocurrency tracking site.",
    url: "https://coinwire.web.app/",
    gitUrl: "https://github.com/caicodes/",
  },
  {
    id: "shesinherapron",
    name: "She's In Her Arpon",
    thumb: "/images/projects/landings/shesinherapron.jpg",
    landing: "/images/projects/thumbs/shesinherapron.jpg",
    desc: "YouTube Influencer blog and ecommerce site.",
    url: "https://shesinherapron.com/",
    gitUrl: "https://github.com/caicodes/",
  },
  {
    id: "modolla",
    name: "Modolla Wallet",
    thumb: "/images/projects/thumb-modolla.jpg",
    landing: "/images/projects/landing-modolla.jpg",
    desc: "modolla info...",
    url: "https://modolla-wallet.web.app/",
    gitUrl: "https://github.com/caicodes/",
  },
  {
    id: "mademoiselle",
    name: "Mademoiselle",
    thumb: "/images/projects/thumbs/mademoiselle.jpg",
    landing: "/images/projects/landings/mademoiselle.jpg",
    desc: "Mademoiselle E-commerce site built with Next.js and hosted on Vercel",
    url: "https://mademoiselle.netlify.app/",
    gitUrl: "https://github.com/caicodes/",
  },
  {
    id: "mademoiselle-collections",
    name: "Mademoiselle Collections",
    thumb: "/images/projects/thumb-mademoiselle-collections.jpg",
    landing: "/images/projects/landing-mademoiselle-collections.jpg",
    desc: "Mademoiselle Collections is a micro-site with collections portal into the Mademoiselle E-commerce site.",
    url: "https://mademoiselle-collections.netlify.app/",
    gitUrl: "https://github.com/caicodes/",
  },
  {
    id: "voya-destinations",
    name: "Voya Destinations",
    thumb: "/images/projects/thumb-voya-destinations.jpg",
    landing: "/images/projects/landing-voya-destinations.jpg",
    desc: "Voya Destinations App for iOS, Android, and Web. This project also included full branding, Flutter, Vue 3 Website, WordPress Microsites and more.",
    url: "https://voya-destinations.web.app/",
    gitUrl: "https://github.com/caicodes/",
  },
  {
    id: "tailwind-templates",
    name: "TailwindCSS Templates",
    thumb: "/images/projects/thumb-tailwind-templates.jpg",
    landing: "/images/projects/landing-tailwind-templates.jpg",
    desc: "This site is a blog with a purpose turned open source project. More information coming soon.",
    url: "https://tailwindcss-templates.vercel.app/",
    gitUrl: "https://github.com/caicodes/",
  },
  {
    id: "dashboard-intelligence",
    name: "Dashboard Intelligence",
    thumb: "/images/projects/thumbs/dashboard-intelligence.jpg",
    landing: "/images/projects/landings/dashboard-intelligence.jpg",
    desc: "The dashboard intelligence project using React and Apex Charts.",
    url: "https://dashboard-intelligence.vercel.app/",
    gitUrl: "https://github.com/caicodes/",
  },
]
